<a href="https://colab.research.google.com/github/DevindiSiwurathna/Numpy/blob/main/Numpy_Shapes_and_Axes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array(24) #create zeroD array

array(24)

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
np.array([[1,1,1],
         [1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

In [ ]:
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [ ]:
numpy_arr=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [ ]:
numpy_arr.shape

(2, 2, 3)

In [ ]:
numpy_arr.ndim

3