<a href="https://colab.research.google.com/github/DevindiSiwurathna/Numpy/blob/main/numpy_create_and_print_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import numpy library
import numpy as np

In [2]:
#first numpy array
first_numpy_array = np.array([1,2,3])

In [4]:
#print first array
print(first_numpy_array)

[1 2 3]


In [5]:
#aRRAY with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#array with ones
array_with_ones = np.ones((3,3))

In [7]:
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[1.820922e-316, 0.000000e+000, 0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000]])

In [10]:
#array with arange method
np_arrange = np.arange(12)
np_arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
#reshape method to change/create array
np_arrange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
#linspace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [16]:
#one dimentional array
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
#two dimensional array
twoD_array = oneD_array.reshape(3,5)
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
#3D array
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])